### ISSUE TITLE
クラウドフレアに対応

### ISSUE THREAD

**Issue by PrefKarafuto** [PrefKarafuto/New_0ch_Plus#1]
クラウドフレアを使用している場合、IPアドレスの環境変数を従来の＄ENV{REMOTE_ADDR}から$ENV{HTTP_CF_CONNECTING_IP}を見るように変更

**Comment by PYU224** [comment]
これはどこのファイルで参照できますか？

**Comment by PrefKarafuto** [comment]
たとえば
https://github.com/PrefKarafuto/New_0ch_Plus/compare/c7ec2e298945a2fdedda808c353c30c292948f11...15a29cb955b8705a59a82f235dac1f4a22576600
ここの140、163，273とかですね
このファイルでそれ以外の差がないのに差分扱いされている部分は文字コードをShift-JISからUTF-8にした際の影響です。

**Comment by PYU224** [comment]
ありがとうございます。
こう書くのですね。

**Comment by PYU224** [comment]
参考になりました。
完全に理解できた訳ではありませんが重ねてありがとうございます。
https://support.cloudflare.com/hc/ja/articles/200170786-%E5%85%83%E3%81%AE%E8%A8%AA%E5%95%8F%E8%80%85IP%E3%82%92%E5%BE%A9%E5%85%83%E3%81%99%E3%82%8B
