### ISSUE TITLE
ソースコード中の日本語表記に係る"\"について

### ISSUE THREAD

**Issue by PrefKarafuto** [PrefKarafuto/New_0ch_Plus#12]
このスラッシュはファイルの文字コードがShift-JISの場合に文字化け防止用に必要なものであるので、UTF-8に変えた今では不要です。
抜いてしまって問題ありません。

**Comment by goodpotatosystems** [comment]
その旨を現在 https://github.com/PrefKarafuto/New_0ch_Plus/issues/13 で整備中のドキュメントに記載して、このIssueをCloseしたいと思いますが、いかがでしょうか？

**Comment by PrefKarafuto** [comment]
ではそちらでやりましょう
