### ISSUE TITLE
リリースサイクルについて

### ISSUE THREAD

**Issue by goodpotatosystems** [PrefKarafuto/New_0ch_Plus#17]
リリースはどのタイミングで行いますか？  
機能全てを作り切ってからはさすがに時間がかかりますし、重要な機能を1つ実装したらその都度リリースしてフィードバックをお願いするのもアリかと思います。

**Comment by PrefKarafuto** [comment]
それでいいと思います
当プロジェクトで最初にリリースする「ぜろちゃんねるプラス」のバージョンはどうしましょう
旧ぜろちゃんねるプラスを引き継いで0.8.xとしましょうか

**Comment by goodpotatosystems** [comment]
それが分かりやすくてよいと思います。

**Comment by PYU224** [comment]
私も同意見です。

**Comment by PrefKarafuto** [comment]
目玉機能として管理画面からのレス検索・削除ですかね
ノヒケーが食らったような各スレへの連投荒らしに対処しやすくなります

**Comment by PrefKarafuto** [comment]
こんな風に管理画面での実装を考えています。
ただしこれはまだ入力画面だけで、肝心の検索・表示・削除機能自体は全く手つかずですが・・・
![image](https://user-images.githubusercontent.com/122600023/213473749-aefefa82-7c8a-4b52-97b2-269069c7c91a.png)

**Comment by goodpotatosystems** [comment]
よろしければ、大まかに機能ごとにリリースを行う旨を現在 https://github.com/PrefKarafuto/New_0ch_Plus/issues/13 で整備中のドキュメントに記載して、このIssueをCloseしたいと思いますが、いかがでしょうか？  
(@PrefKarafuto 師のOKが出たらCloseします)  
  
検索&削除についての話題は別にIssue #19 を切りました。

**Comment by PrefKarafuto** [comment]
お願いいたします。

**Comment by goodpotatosystems** [comment]
ドキュメントに記載したのでCloseします。
