### ISSUE TITLE
宣伝記事と動画で寄せられた質問

### ISSUE THREAD

**Issue by Rumakote** [PrefKarafuto/New_0ch_Plus#18]
記事や動画のコメントで来た質問を転載して回答を出しましょうというIssueです。

**Comment by PrefKarafuto** [comment]
１はUTF-8化がうまく行けば問題にはならないと思います。
2に関して、サーバーのスペックは低くても問題なく動きます。VPSのような高度なものでなく、Perl/CGI可の無料レンタルサーバー程度でも動作に困ることはないでしょう。ストレージ的には250MBぐらいでも持て余す程度に余裕が有ります(樺太BBSは諸々含めて6MBほど)。

**Comment by Rumakote** [comment]
回答に感謝です。
さっそく伝えてきます。
