### ISSUE TITLE
変数が宣言されていない、という旨のエラーが頻出する

### ISSUE THREAD

**Issue by PrefKarafuto** [PrefKarafuto/New_0ch_Plus#23]
たとえば
Global symbol "$textã—ã¾ã™" requires explicit package name (did you forget to declare "my $textã—ã¾ã™"?) at ./admin/bbs.thread.pl line 367.
というエラーが出る場合
```
$Page->Print("<tr><td colspan=3>以下のスレッドを$textします。</td></tr>");
```
の$textの後ろに\\を加えて
```
$Page->Print("<tr><td colspan=3>以下のスレッドを$text\します。</td></tr>");
```
としてください。
UTF-8化に伴ってこのエラーが多発すると思われますので、可能であれば$Page->Print中に記述される変数全体にこの処理を適用したほうがいいかもしれません。

**Comment by goodpotatosystems** [comment]
最終的な対処は各位にお任せしますが、Perlなら文字列中の変数は${text}みたいに明示できた気がします。
