### ISSUE TITLE
Capcha認証改良

### ISSUE THREAD

**Issue by PrefKarafuto** [PrefKarafuto/New_0ch_Plus#27]
暫定的にhCapcha認証機能が実装されましたが、更に詰めて改良していきたいと思います。
実装案
+ reCapcha、PerlモジュールによるCapchaも追加。
+ 設定画面の改良
+ 各種キーのエラーチェック
+ 専ブラ越しにCapcha認証出来るようにする

**Comment by PYU224** [comment]
recaptchaは早い段階で実装できると思います。
他はやってみるつもりですが自信がありません。

**Comment by PrefKarafuto** [comment]
セキュリティの問題から、hCapcha設定の場所をシステム設定側に移そうと思います

**Comment by PYU224** [comment]
分かりました。

**Comment by PrefKarafuto** [comment]
サイトキー、シークレットキーの入力はシステム設定で行い、掲示板毎の適応可否設定を掲示板設定->制限・規制設定で行うようにしました。
これによりシークレットキーが非公開の場所に保存されるため、セキュリティ的にも問題なくなったと思います。
あと、キーが設定されていないと掲示板設定側ではチェックを入れられないようにしました

**Comment by PYU224** [comment]
お疲れ様です。
システム設定という手がありましたか。
