### ISSUE TITLE
新機能の意見・提案

### ISSUE THREAD

**Issue by PrefKarafuto** [PrefKarafuto/New_0ch_Plus#3]
追加してほしい機能の意見などはこちらに

**Comment by PYU224** [comment]
優先順位は低いですがスマホ対応のレスポンシブデザインにはしたいです

**Comment by PYU224** [comment]
こちらのスクリプトで実現されている事柄ですが、SNSボタンの設置やURLのプレビュー機能、Captcha機能の追加が挙げられます。
できれば設定でオンオフができるように。
https://github.com/Rumakote/YakumoBBS-custom

**Comment by koushinkyouto** [comment]
ﾜｯﾁｮｲの追加を希望します
あとスレ立て時にﾜｯﾁｮｲやID無し、強制開示等を設定できる機能も追加してほしいです

**Comment by Rumakote** [comment]
使ってみて思ったんですが、最初のログインの際に固定で「User:Administrator Pass:zeroch」はやめていきなりログインか、あるいはパスワードとユーザー名の設定画面に入った方がとっつきやすいと思います

**Comment by koushinkyouto** [comment]
キャップ毎の権限をもう少し細かくしてほしいです。

**Comment by koushinkyouto** [comment]
コマンドを用いて文字色やフォントを調整する機能を追加してほしいです

**Comment by koushinkyouto** [comment]
レスに対して絵文字で反応できる機能も追加してほしいです

**Comment by PrefKarafuto** [comment]
Discussionsに「ぜろちゃんねるプラス総合」を建てました。
https://github.com/PrefKarafuto/New_0ch_Plus/discussions/10

**Comment by goodpotatosystems** [comment]
discussionsに意見・提案を集約する場合、このIssueはCloseしてよいと思いますが、いかがでしょうか？  
※もしCloseするのであれば既にここに書かれたものはdiscussionsに持っていきましょう

**Comment by PYU224** [comment]
Closeしても良いと思います。
