### ISSUE TITLE
自分だけでは解決できない難しい不具合の報告

### ISSUE THREAD

**Issue by Rumakote** [PrefKarafuto/New_0ch_Plus#33]
一応こういうIssueを作ってみました。
不要ならCloseして構いません。

**Comment by Rumakote** [comment]
掲示板を作って、設定画面にアクセスしようとすると

> Wide character at ./module/setting.pl line 63.

と出てしまい設定に入れません。
検索してもEncode::decode関数について記述されたページが少ないので解決方法が分かりません。
無力で申し訳ないのですが、問題をここに投げさせていただきます。

**Comment by PrefKarafuto** [comment]
遅ればせながら、エラーが出る部分をCOしました。

**Comment by PrefKarafuto** [comment]
新たに発見しましたが、掲示板管理画面のスレッド一覧で、スレッドを停止/再開させようとすると何故か画面全体が文字化けします。それ以外の、属性付与やDAT落ちでは発生は確認できませんでした。また文字化けした状態で別の管理メニューに飛ぶと、その時点で解消します。

**Comment by PrefKarafuto** [comment]
どうやらthread.pl、dat.pl辺りで文字コードの設定がうまく行ってないのが原因みたいですが、なんかややこしくなっているのでしばらく掛かりそうです

**Comment by PrefKarafuto** [comment]
掲示板の各種編集メニューで、ヘッダ・フッタ・META編集のみで、確認ボタンを押しても内容がプレビューに反映されずまっさらの状態になり、変更ボタンを押すとデータが削除され中身のないUTF8ファイルに上書きされるバグを確認しています。
しばらく格闘しましたが如何ともしがたかったためココに投げさせていただきます。

**Comment by PrefKarafuto** [comment]
修正に成功した（と思います）ので、テストお願いいたします。

**Comment by Rumakote** [comment]
現在ヘッダでテスト中ですが、プレビュー・変更ともに問題なさそうな感じです。

**Comment by PrefKarafuto** [comment]
ありがとうございます。
現時点で把握しているバグは一通り潰したので、他の機能でもデバッグをお願いしたいです。
