### ISSUE TITLE
デフォルトで梱包されているプラグインの扱い

### ISSUE THREAD

**Issue by PrefKarafuto** [PrefKarafuto/New_0ch_Plus#37]
0.8.ｘでは
・BE関係のプラグインを廃止
・スパムキラー関連、画像表示、引用強調表示、おみくじ、UA表示を本体に取り込み
を考えていますがどうでしょうか

**Comment by PrefKarafuto** [comment]
その他のプラグイン一覧はこちら
https://ja.osdn.net/projects/zerochplus/wiki/Codes

**Comment by PYU224** [comment]
良いと思います。
