### ISSUE TITLE
モジュールのリネームについて

### ISSUE THREAD

**Issue by goodpotatosystems** [PrefKarafuto/New_0ch_Plus#4]
モジュール名のリネームは今後の開発効率に影響してくるので、早いうちに着手した方がよいと思われます。  
@PrefKarafuto 師が https://github.com/PrefKarafuto/New_0ch_Plus/blob/e5ed74bc767fc6e37b3866907268fd7223404624/test/module/README.md にまとめてくれたものを参考にして案を作ってみました。  
とりあえず意見を募集します。  
# 改名案

before|after|機能  
---|---|---  
athelas     |plugin     |プラグイン管理  
baggins     |thread     |スレッド情報管理  
balrogs     |search     |検索  
celeborn    |archive    |過去ログ管理  
cidr_list   |cidr_list   |携帯IPのCIDRチェック  
constant    |constant    |定数の定義情報  
denethor    |banner    |バナー管理  
earendil    |file_utils    |ファイル操作ユーティリティ  
elves       |security       |管理セキュリティの管理  
faramir     |user     |アクセスユーザ管理  
galagriel   |data_utils   |汎用データ変換・取得  
gandalf     |notice     |ユーザ通知管理  
gondor      |dat      |datファイル管理  
httpservice |http_service |httpサービス  
imrahil     |log     |ログ管理  
isildur     |setting     |SETTINGデータ管理  
legolas     |header_footer_meta     |ヘッダ・フッタ・META管理  
melkor      |system      |システムデータ管理  
nazguls     |bbs_info     |掲示板情報管理  
newrelease  |update_notice  |アップデート通知  
orald       |error_info       |エラー情報管理モジュール  
peregrin    |manager_log    |管理ログデータの管理  
radagast    |cookie    |cookie管理  
samwise     |form     |フォーム情報管理  
session     |session     |セッション管理  
thorin      |buffer      |バッファ出力管理  
ungoliants  |cap  |キャップ管理  
vara        |post_service        |掲示板書き込み支援  
varda       |bbs_service       |bbs.cgi支援  
wormtongue  |ng_word  |NGワード管理  

よりよい名前があるかもしれませんが、とりあえず取り急ぎ。

**Comment by PrefKarafuto** [comment]
わかりやすくて良いと思います。
加えて、mordorフォルダにもsauron.plなるモジュールがあるので、
before|after|機能
---|---|---
sauron|admin_cgi_base|管理CGIのベース
  
を提案します。

**Comment by goodpotatosystems** [comment]
そのモジュールには気付きませんでした……  
よいと思います。

**Comment by PYU224** [comment]
私も良いと感じます。

**Comment by goodpotatosystems** [comment]
追加でいくつか。
1つのファイルに複数パッケージが入っててこれがまた変な名前なので変えていきます的な内容です。

0. ファイル名だけでなくパッケージ名も適宜変更する。
1. nazgulsに「カテゴリ情報管理」のANGMARなるパッケージが含まれているのでこれをCATEGORY_INFOに変更する
2. ungoliantsに「キャップグループ情報管理」のSHELOBなるパッケージが含まれているのでこれをCAP_GROUPに変更する
3. elvesに「ユーザ情報管理」のGLORFINDELなるパッケージが含まれているのでこれをUSER_INFOに変更する
4. elvesに「グループ情報管理」のGILDORなるパッケージが含まれているのでこれをGROUP_INFOに変更する
5. elvesに「セキュリティインタフェイス」のARWENなるパッケージが含まれているのでこれをSECURITYに変更する
6. bagginsに「現行スレッド情報管理」のBILBOなるパッケージが含まれているのでこれをTHREADに変更する
7. bagginsに「プールスレッド情報管理」のFRODOなるパッケージが含まれているのでこれをPOOL_THREADに変更する

**Comment by goodpotatosystems** [comment]
とりあえずブランチ切っときました

**Comment by goodpotatosystems** [comment]
追加。  
・mordorフォルダをadminに名称変更

**Comment by goodpotatosystems** [comment]
手が空いている芋がいたら上記ブランチのテストを手伝っていただけると助かります。  
一応注意しながら置換してますが万が一もあるので。  
問題ないようならプルリク出します。

**Comment by PrefKarafuto** [comment]
galadriel.plの置換忘れが有るようです

**Comment by PrefKarafuto** [comment]
あとついでにbuffer.plをbuffer_output.plにしてはどうでしょうか

**Comment by PrefKarafuto** [comment]
とりあえずは問題なさそうですね

**Comment by goodpotatosystems** [comment]
マージしたので一旦閉じます
