### ISSUE TITLE
PHPへの移植について

### ISSUE THREAD

**Issue by goodpotatosystems** [PrefKarafuto/New_0ch_Plus#5]
機能追加をしていくなら先にPHPへ移植をした方が追加ぶんが無駄にならない気がしますが、いかがでしょうか

**Comment by PrefKarafuto** [comment]
可能であればそれが一番よいと思います。
ただそうなると、私はPHPに詳しくないので、他のコントリビューター様やコラボレーター様に頼るところ大となろうかと、思います。

**Comment by PYU224** [comment]
PHPの方がいじる分には簡単ですが、Perl→ PHPへの書き換えはかなり難しい作業になるでしょう。
以下のページが参考になると思われます。
https://haik.oi21.net/index.php?perl2php
https://tgws.plus/prog/prog19.html

**Comment by PYU224** [comment]
私は一応PHPとPerlはできます。
ただこの0ch+が相手ですと量が多いので非常に時間がかかって難しいと思いますが。

**Comment by goodpotatosystems** [comment]
Perl見ながら書き換えるのと、機能を棚卸しして同じのをゼロベースでPHPに書き直すの、どちらが楽ですかね……

**Comment by PrefKarafuto** [comment]
私も書き換えるなら出来る限り協力する所存ですが、当プロジェクトは一般向けで開発を行っていくつもりなので、外部のPHPに強い有志にも協力を仰ぐことを視野に入れるべきかと。
流石に書き換え全般をissueに丸投げは出来ないので。

**Comment by PrefKarafuto** [comment]
https://shade-search.com/sts/term/term.php?noform=vhNB6oPvMD
こういう書き換え補助PHPは有りますが、あくまで補助なので、勿論それですぐ動くわけもないようですね。
ただ手間は格段に減るんじゃないかと思います。

**Comment by goodpotatosystems** [comment]
いきなり外部から協力者を取れるとも限らないしやはりPHP書き換えは最初は難しいですかね。  
別のタイミングでやるとしたら、機能追加を一通り終えたらを考えていますか？それとも機能追加と並行してを考えていますか？

**Comment by PYU224** [comment]
並行はやめた方がいいと思います。
某銀行はそれで大変な事になっているらしいですし。

**Comment by PrefKarafuto** [comment]
そうですね、まず機能開発に注力したほうが安全ですかね。

**Comment by goodpotatosystems** [comment]
了解しました。その方向で私も進めます。  

機能を作り終えて、かつ機能リクエストが1ヶ月来なくなった時点でPHP移植開始とか、タイミングは決めた方がよいと思います。

**Comment by PrefKarafuto** [comment]
賛成です。

**Comment by PYU224** [comment]
賛成です。
今は人が少なく、その作業は最終的に人数を揃えてやった方が効率が良いでしょうからね。

**Comment by goodpotatosystems** [comment]
上記の通り
>機能を作り終えて、かつ機能リクエストが1ヶ月来なくなった時点でPHP移植開始

でよろしければ、その旨を現在 #13 で整備中のドキュメントに記載して、このIssueをCloseたいと思います。  
よろしいでしょうか？(@PrefKarafuto 師のOKが出たらCloseします)

**Comment by PrefKarafuto** [comment]
ではその方向で進めていきましょう。

**Comment by goodpotatosystems** [comment]
ドキュメントに記載したのでCloseします。
