### ISSUE TITLE
忍法帖をログのcgiに紐付ける機能の追加

### ISSUE THREAD

**Issue by frictionsmooth** [PrefKarafuto/New_0ch_Plus#55]
現在忍法帖と書き込みを紐付ける為には面倒な手順を踏まないとできないのでログのcgiと紐付けてほしい。
そうすればIDなしスレでの規制やコマンドの発動が簡単になり開発が楽になると思います。

**Comment by PrefKarafuto** [comment]
その場合、logフォルダに置かれる.cgiに、新しく忍法帖IDを保存する箇所を追加する必要があります
一応、現在のログファイルの構成は
名前<>メール<>日付・時刻・ID<>本文(30字まで)<>スレタイ(あれば)<>ホスト<>IP<>本文文字数<>UA
となっています

**Comment by PrefKarafuto** [comment]
互換性の観点から追加する場合は一番うしろで
名前<>メール<>日付・時刻・ID<>本文(30字まで)<>スレタイ(あれば)<>ホスト<>IP<>本文文字数<>UA<>忍法帖ID(セッションID)
という感じですかね

**Comment by PrefKarafuto** [comment]
ログファイルに忍法帖IDを保存するセクションを追加しました
