### ISSUE TITLE
プロジェクトに「ぜろちゃんねるプラス」という名称を使わないでほしい

### ISSUE THREAD

**Issue by windyakin** [PrefKarafuto/New_0ch_Plus#58]
## 概要

プロジェクトに「ぜろちゃんねるプラス」という名称を使わないでほしいです

## なぜか

* 開発者・開発思想が異なる Fork プロジェクトにもかかわらず Fork 元と同じ名前を利用することで利用者に混乱が生じる
* 我々（ぜろちゃんねるプラス）が今後何かしらの機能改善のリリースをする際にバージョンが被る可能性がある

すでに開発は凍結という扱いをしていますが、今後また脆弱性の対応パッチを当てる必要があった際にアナウンスやバージョンを付ける際に混乱を来す場合があります。

このお願いに法的根拠などはありませんが、少なくともスクリプトの利用者がプロジェクトが異なることを明確に理解できた上で、選択できることに意義があると理解していただければと思います。

**Comment by PrefKarafuto** [comment]
早急に対応いたします

**Comment by PrefKarafuto** [comment]
名称を「EXぜろちゃんねる（ex0ch）」に変更
