### ISSUE TITLE
プロジェクトの宣伝について

### ISSUE THREAD

**Issue by Rumakote** [PrefKarafuto/New_0ch_Plus#9]
このプロジェクトって私が知っている外部のプログラマの集いや、ブログの方で宣伝しても良いのでしょうか？

**Comment by PrefKarafuto** [comment]
是非お願いいたします。
READMEでも書きましたが、一般向けとして開発を行っていくつもりですので、宣伝は大変ありがたいです。

**Comment by Rumakote** [comment]
分かりました。

**Comment by Rumakote** [comment]
ささやかなお願いですが、私の掲示板プロジェクトの方も見て改良に役立ててくれたらと思います。
https://github.com/Rumakote/YakumoBBS-custom

**Comment by PrefKarafuto** [comment]
貴スクリプトには良い機能が有りますし、是非取り入れたいとおもいます。

**Comment by Rumakote** [comment]
ありがとうございます。
0ch+はいじってて思ったんですが、狙ってやっているのかと思いたくなるくらいスクリプトが分かりにくいので、もし0ch+でのカスタムが頓挫したら私のカスタムした掲示板をベースにやると良いかもしれません。
使ってみると分かるんですがYakumoBBSはシンプルです。

**Comment by PrefKarafuto** [comment]
そうですね、そのへんは今後のPHPへの移植辺りで対処できたらと思います。

**Comment by Rumakote** [comment]
記事を作ってTwitterやDiscordで宣伝しています。
https://kusaimara.com/2023/01/zerochplus.html

**Comment by Rumakote** [comment]
動画でも募集をかけてみました。

・Youtube
https://youtu.be/N12QP-L7ik0
・ニコニコ動画
https://www.nicovideo.jp/watch/sm41669731

**Comment by goodpotatosystems** [comment]
今のところ問題がないならCloseしてもよいと思いますが、いかがですか？  
しばらく様子見て人が来ないようならまた考える感じです。

**Comment by PrefKarafuto** [comment]
そうですね、今後はディスカッションの方で対応することにしましょう。

**Comment by Rumakote** [comment]
分かりました。
